In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
result = arr **2    # Vectorization
result

array([ 1,  4,  9, 16, 25])

In [5]:
result + 10   # Broadcasting

array([11, 14, 19, 26, 35])

In [10]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([7,8,9])
result = arr1 + arr2  #Broadcasting arr1 across arr2
result

array([[ 8, 10, 12],
       [11, 13, 15]])

In [12]:
# simulating the dataset (5 samples , 3 features)
data = np.array([[10,20,30],
                 [40,50,60],
                 [20,30,40],
                 [25,45,65],
                 [70,80,90]])
# calculating Mean and standard deviation for each feature (coloumn)
mean = data.mean(axis=0)
std = data.std(axis=0)

#Normalization the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.10150023 -1.21987509 -1.29306549]
 [ 0.3352392   0.24397502  0.14367394]
 [-0.62258709 -0.73192505 -0.81415234]
 [-0.38313051  0.          0.38313051]
 [ 1.77197863  1.70782513  1.58041337]]
