In [1]:
import numpy as np
arr = np.array([10,22,34,48])

In [2]:
np.mean(arr) #Compute the mean (average) of an array.

np.float64(28.5)

In [3]:
np.std(arr) # Compute the standard deviation of an array.

np.float64(14.097872179871684)

In [4]:
np.var(arr) #Compute the variance of an array.

np.float64(198.75)

In [5]:
np. min(arr) #Compute the minimum value of an array.

np.int64(10)

In [6]:
np.max(arr) #Compute the maximum value of an array.

np.int64(48)

In [7]:
np.sum(arr) #Compute the sum of all elements in an array.

np.int64(114)

In [8]:
np.prod(arr) #  Compute the product of all elements in an array

np.int64(359040)

In [9]:
np.median(arr) # Compute the median of an array.

np.float64(28.0)

In [10]:
np.percentile(arr , 100) #Compute the percentile of an array.

np.float64(48.0)

In [11]:
np.argmin(arr) #Return the index of the minimum value in an array.

np.int64(0)

In [12]:
np.argmax(arr) # Return the index of the maximum value in an array.

np.int64(3)

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
np.corrcoef(arr1 , arr2) #Compute the correlation coefficient matrix of two arrays.

array([[1., 1.],
       [1., 1.]])

In [14]:
np.unique(arr) #Find the unique elements of an array.

array([10, 22, 34, 48])

In [15]:
np.diff(arr) # Compute the n-th differences of an array.

array([12, 12, 14])

In [16]:
np.cumsum(arr)#Compute the cumulative sum of an array.

array([ 10,  32,  66, 114])

In [17]:
np.linspace(0,10,5) #Create an array with evenly spaced numbers over a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.log(arr) # Compute the natural logarithm of an array.

array([2.30258509, 3.09104245, 3.52636052, 3.87120101])

In [19]:
np.exp(arr) #Compute the exponential of an array.

array([2.20264658e+04, 3.58491285e+09, 5.83461743e+14, 7.01673591e+20])