In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(np.sum(arr, axis=0)) # Column-wise sum
print(np.sum(arr,axis=1)) # Row-wise sum

[12 15 18]
[ 6 15 24]


In [14]:
# Indexing in Multidimensional Arrays
print(arr[1][2])
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns


6
[[2 3]
 [5 6]]


In [16]:
arr3D = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])

In [19]:
print(arr3D [:,0,:])

[[1 2 3]
 [7 8 9]]


In [20]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])