In [5]:
import numpy as np

In [14]:
# 1-D array
arr1 = np.array([1,2,3,4,5])
# 2-D array
arr2 = np.array([[1,2,3] , [4,5,6]])
arr1
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#Types of arrays
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.full((3,2) , 7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [24]:
np.eye(3)  # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(1 , 10, 2)

array([1, 3, 5, 7, 9])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Arrays Properties

In [36]:
myarr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
myarr.shape

(3, 3)

In [38]:
myarr.size # total numbers

9

In [41]:
myarr.ndim #dimensional

2

In [43]:
myarr.dtype

dtype('int64')

In [44]:
# Changing data types

In [47]:
myarr = np.array([[1,2,3] , [4,5,6] , [7,8,9]], dtype = 'float32') #Explicit tyoe
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [50]:
n = myarr.astype('float64') #covert int to float
n.dtype

dtype('float64')

In [53]:
myarr.dtype

dtype('float32')

In [54]:
#  Reshaping and Flattening Arrays

In [60]:
myarr = np.array([[1,2,3] , [4,5,6] , [7,8,9] ,[10,11,12]])
myarr.shape

(4, 3)

In [64]:
myarr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])